AWSTemplateFormatVersion: '2010-09-09'
Description: 'template for secrets manager'

Parameters:
    SecretName:
        Description: 'name of secret manager'
        Type: String
        
    
Resources:
    TwitterSecrets:
        Type: AWS::SecretsManager::Secret
        Properties: 
            Name: !Ref SecretName
            Description: 'Secrets of twitter developer account'
            SecretString: '{"id":"twitter-id","secret":"twitter-secret"}'